Bug Fix: Fix the issue with removing the equipments which are not available
vojtamolda/homebridge-ecobee3-sensors pull request #46
Opened 2023-05-10 05:58 UTC by aminry

After restarting the homebridge we might need to remove the devices and this would fix the bug that if fail to remove the device.

2023-05-10 11:55 UTC, vojtamolda commented on package.json
> -  "version": "0.1.11",
I usually bump up the version number myself when I do a release and publish to NPM.

2023-05-10 11:57 UTC, vojtamolda requested changes
Thanks a lot for the PR. There's a few small details that need changing. I think only the changes in `platform.js` are needed here.

2023-05-10 11:57 UTC, vojtamolda commented on package-lock.json
> -  "name": "homebridge-ecobee3-sensors",
This is probably left over from your own package.

2023-05-10 15:20 UTC, aminry commented on package-lock.json
> -  "name": "homebridge-ecobee3-sensors",
removed changes

2023-05-10 15:21 UTC, aminry commented on package.json
> -  "version": "0.1.11",
reverted the changes

2023-05-11 02:42 UTC, merged

2023-05-11 02:42 UTC, vojtamolda commented
Thanks!

2023-05-11 02:45 UTC, vojtamolda commented
Just pushed version 0.1.12 with the fix to NPM.